#!/bin/bash

CLDB=../src/cldb

if [ -n "$OPSYAML" ]; then
	python $CLDB -o $OPSYAML
	exit 1
fi

YAMLFILE="./ip.yaml"
if ! [ -f "$YAMLFILE" ]; then
	make clean
	make
fi
if [ -z "$NODE" ];then
	echo "NODE not found..."
	exit 1
fi
if [ -z "$PORT" ];then
	echo "PORT not found..."
	exit 1
fi
if [ -z "$HC" ]; then
	echo "HASH COLUMN not found..."
	exit 1
fi
if [ -z "$DB" ]; then
	echo "DB not found..."
	exit 1
fi
if [ -z "$TABLE" ]; then
	echo "TABLE not found..."
	exit 1
fi
if [ -n "$NOTICE" ]; then
	NOTICE="-s $NOTICE"
fi
NODEIP=$(docker network inspect $NODE | jq -r ".[].IPAM.Config[].Gateway")
if [ -n "$NORE" ]; then
	NORE="-n "
fi

echo "ADD Node IP Address: $NODEIP"
cat $YAMLFILE

USER=root
PASSWORD=mysql
python $CLDB 	\
		--ip $NODEIP \
		--port $PORT \
		--yaml_path $YAMLFILE \
		--hash_column $HC \
		--db $DB \
		--table $TABLE \
		--mode ${MODE:-"add"} \
		$NOTICE \
		--secret_once \
		--user $USER \
		--password $PASSWORD \
		-v ${VCOUNT:-10} \
		$NORE \


