#!/bin/bash

YAMLFILE="./ip.yaml"
if ! [ -f "$YAMLFILE" ]; then
	make clean
	make
fi
NODE2IP=$(docker network inspect node2 | jq -r ".[].IPAM.Config[].Gateway")

echo "Node2 IP Address: $NODE2IP"
cat $YAMLFILE

python add_node.py $NODE2IP $YAMLFILE
