CREATE DATABASE sharding;
USE sharding;

CREATE TABLE user (
	id BIGINT NOT NULL AUTO_INCREMENT,
	username CHAR(10) NOT NULL,
	comment VARCHAR(100),
	start DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);
